#! /bin/bash

# Usage: ./publish <CruzID>
# Will prompt for blue password
REMOTE="$1@sftp.ic.ucsc.edu"
RSH='ssh'
RSYNC='/usr/bin/rsync -avz'
WWWDIR='/afs/cats.ucsc.edu/www/ospo'
PROD='prod/public_html'
DEV='dev/public_html'

#(pushd $ACADEMIC; academic import --bibtex ospo.bib; python3 addpdfs.py; hugo; popd)

# Assume this is executed at the top directory of the repository
# Swap commands depending on whether it's production or development
#$RSYNC -e "$RSH" ./public/* $REMOTE:$WWWDIR/$DEV
$RSYNC -e "$RSH" ./public/* $REMOTE:$WWWDIR/$PROD
