#! /bin/bash

#REMOTE='carlosm@raindance.cse.ucsc.edu'
#REMOTE='carlosm@soe.ucsc.edu'
REMOTE='carlosm@riverdance.soe.ucsc.edu'
RSH='ssh'
RSYNC='/usr/bin/rsync -avz'
ACADEMIC=$HOME/git/carlosmalt/ucsc-ospo

(pushd $ACADEMIC; academic import --bibtex ospo.bib; python3 addpdfs.py; hugo; popd)
$RSYNC -e "$RSH" $ACADEMIC/public/* $REMOTE:.html/dev/
